import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
import NextAuthProvider from "src/provider/NextAuthProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} max-w-6xl mx-auto p-4`}>
        <NextAuthProvider>
          <Header />
          <main style={{ minHeight: "80vh" }}>{children}</main>
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
